# FINANCIAL CONTAGION BEHAVIOUR

In [66]:
#Load Modules
import networkx as nx
import pandas as pd
import numpy as np

In [67]:
#Import datasets - All Data and Pre, During and Post the US subprime crisis of 2008
fcb_alldata = pd.read_csv("Financial Contagion Behaviour - All Data.csv")
fcb_predata = pd.read_csv("Financial Contagion Behaviour - Pre Crisis.csv")
fcb_duringdata = pd.read_csv("Financial Contagion Behaviour - During Crisis.csv")
fcb_postdata = pd.read_csv("Financial Contagion Behaviour - Post Crisis.csv")

## 1. Network formation of the entire dataset (All Data)

In [68]:
#All Data
fcb_alldata

,Date,S&P Price,FTSE Price,S&P Log Returns,FTSE Log Returns,Co-movement symbol,Co-movement mode,Source,Target,Weights
0,11-01-2006,1294.18,5731.50,0.35%,0.75%,P,NPNPP,NPNPP,PNPPN,13
1,12-01-2006,1286.06,5735.10,-0.63%,0.06%,N,PNPPN,PNPPN,NPPNN,18
2,13-01-2006,1287.61,5711.00,0.12%,-0.42%,N,NPPNN,NPPNN,PPNNP,15
3,17-01-2006,1282.93,5699.00,-0.36%,-0.21%,P,PPNNP,PPNNP,PNNPP,41
4,18-01-2006,1277.93,5663.70,-0.39%,-0.62%,P,PNNPP,PNNPP,NNPPP,41
...,...,...,...,...,...,...,...,...,...,...
1804,02-05-2013,1597.59,6460.71,0.94%,0.15%,P,PPNNP,PPNNP,PNNPP,41
1805,03-05-2013,1614.42,6521.46,1.05%,0.94%,P,PNNPP,PNNPP,NNPPP,41
1806,07-05-2013,1625.96,6557.30,0.71%,0.55%,P,NNPPP,NNPPP,NPPPP,31
1807,08-05-2013,1632.69,6583.48,0.41%,0.40%,P,NPPPP,NPPPP,PPPPN,36
1808,09-05-2013,1626.67,6592.74,-0.37%,0.14%,N,PPPPN,PPPPN,PPPNP,103

In [69]:
fcb_alldata.corr(method = 'pearson') #Very high correlation for movements in prices between S&P500 and FTSE100

            S&P Price  FTSE Price   Weights
S&P Price    1.000000    0.950422  0.067759
FTSE Price   0.950422    1.000000  0.050965
Weights      0.067759    0.050965  1.000000

In [70]:
#Pulling out the source nodes, target nodes and weights from the all data dataframe

fcb_alldata2 = fcb_alldata.loc[:,["Source","Target","Weights"]]
fcb_alldata2

     Source Target  Weights
0     NPNPP  PNPPN       13
1     PNPPN  NPPNN       18
2     NPPNN  PPNNP       15
3     PPNNP  PNNPP       41
4     PNNPP  NNPPP       41
...     ...    ...      ...
1804  PPNNP  PNNPP       41
1805  PNNPP  NNPPP       41
1806  NNPPP  NPPPP       31
1807  NPPPP  PPPPN       36
1808  PPPPN  PPPNP      103

[1809 rows x 3 columns]

In [71]:
#Drawing out the network structure for all data dataframe

G_alldata = nx.from_pandas_edgelist(fcb_alldata2,source='Source',target='Target', edge_attr='Weights', create_using=nx.DiGraph())
print(G_alldata)

DiGraph with 32 nodes and 64 edges

## 2. Network formation with the 'Pre Subprime Crisis' dataset

In [72]:
#Pre-crisis data
fcb_predata

,Date,S&P Price,FTSE Price,S&P Log Returns,FTSE Log Returns,Co-movement symbol,Co-movement mode,Source,Target,Weights
0,11-01-2006,1294.18,5731.5,0.35%,0.75%,P,NPNPP,NPNPP,PNPPN,3
1,12-01-2006,1286.06,5735.1,-0.63%,0.06%,N,PNPPN,PNPPN,NPPNN,4
2,13-01-2006,1287.61,5711.0,0.12%,-0.42%,N,NPPNN,NPPNN,PPNNP,4
3,17-01-2006,1282.93,5699.0,-0.36%,-0.21%,P,PPNNP,PPNNP,PNNPP,10
4,18-01-2006,1277.93,5663.7,-0.39%,-0.62%,P,PNNPP,PNNPP,NNPPP,10
...,...,...,...,...,...,...,...,...,...,...
296,23-03-2007,1436.11,6339.4,0.11%,0.34%,P,PPPNP,PPPNP,PPNPN,7
297,26-03-2007,1437.50,6291.9,0.10%,-0.75%,N,PPNPN,PPNPN,PNPNN,4
298,27-03-2007,1428.61,6292.6,-0.62%,0.01%,N,PNPNN,PNPNN,NPNNP,2
299,28-03-2007,1417.23,6267.2,-0.80%,-0.40%,P,NPNNP,NPNNP,PNNPP,4
300,29-03-2007,1422.53,6324.2,0.37%,0.91%,P,PNNPP,PNNPP,NNPPP,10

In [73]:
#Pulling out the source nodes, target nodes and weights from the pre crisis data df

fcb_predata2 = fcb_predata.loc[:,["Source","Target","Weights"]]
fcb_predata2

    Source Target  Weights
0    NPNPP  PNPPN        3
1    PNPPN  NPPNN        4
2    NPPNN  PPNNP        4
3    PPNNP  PNNPP       10
4    PNNPP  NNPPP       10
..     ...    ...      ...
296  PPPNP  PPNPN        7
297  PPNPN  PNPNN        4
298  PNPNN  NPNNP        2
299  NPNNP  PNNPP        4
300  PNNPP  NNPPP       10

[301 rows x 3 columns]

In [74]:
#Drawing out the network structure for pre crisis data df

G_predata = nx.from_pandas_edgelist(fcb_predata2,source='Source',target='Target', edge_attr='Weights', create_using=nx.DiGraph())
print(G_predata)

DiGraph with 32 nodes and 59 edges

## 3. Network formation with the 'During Subprime Crisis' dataset

In [75]:
#During crisis data
fcb_duringdata

,Date,S&P Price,FTSE Price,S&P Log Returns,FTSE Log Returns,Co-movement symbol,Co-movement mode,Source,Target,Weights
0,02-04-2007,1424.55,6315.50,0.26%,0.12%,P,NPPPP,NPPPP,PPPPP,27
1,03-04-2007,1437.77,6366.10,0.92%,0.80%,P,PPPPP,PPPPP,PPPPN,27
2,04-04-2007,1439.37,6364.70,0.11%,-0.02%,N,PPPPN,PPPPN,PPPNP,30
3,05-04-2007,1443.76,6397.30,0.30%,0.51%,P,PPPNP,PPPNP,PPNPP,31
4,10-04-2007,1448.39,6417.80,0.32%,0.32%,P,PPNPP,PPNPP,PNPPP,31
...,...,...,...,...,...,...,...,...,...,...
490,24-03-2009,806.12,3911.46,-2.06%,-1.05%,P,NNNPP,NNNPP,NNPPN,3
491,25-03-2009,813.88,3900.25,0.96%,-0.29%,N,NNPPN,NNPPN,NPPNP,6
492,26-03-2009,832.86,3925.20,2.31%,0.64%,P,NPPNP,NPPNP,PPNPP,13
493,27-03-2009,815.94,3898.85,-2.05%,-0.67%,P,PPNPP,PPNPP,PNPPP,31
494,30-03-2009,787.53,3762.91,-3.54%,-3.55%,P,PNPPP,PNPPP,NPPPP,27

In [76]:
#Pulling out the source nodes, target nodes and weights from the during crisis data df

fcb_duringdata2 = fcb_duringdata.loc[:,["Source","Target","Weights"]]
fcb_duringdata2

    Source Target  Weights
0    NPPPP  PPPPP       27
1    PPPPP  PPPPN       27
2    PPPPN  PPPNP       30
3    PPPNP  PPNPP       31
4    PPNPP  PNPPP       31
..     ...    ...      ...
490  NNNPP  NNPPN        3
491  NNPPN  NPPNP        6
492  NPPNP  PPNPP       13
493  PPNPP  PNPPP       31
494  PNPPP  NPPPP       27

[495 rows x 3 columns]

In [77]:
#Drawing out the network structure for during crisis data df

G_duringdata = nx.from_pandas_edgelist(fcb_duringdata2,source='Source',target='Target', edge_attr='Weights', create_using=nx.DiGraph())
print(G_duringdata)

DiGraph with 32 nodes and 60 edges

## 4. Network formation with the 'Post Subprime Crisis' Dataset

In [78]:
#Post crisis data
fcb_postdata

,Date,S&P Price,FTSE Price,S&P Log Returns,FTSE Log Returns,Co-movement symbol,Co-movement mode,Source,Target,Weights
0,01-04-2009,811.08,3955.61,1.64%,0.75%,P,PPPPP,PPPPP,PPPPP,116
1,02-04-2009,834.38,4124.97,2.83%,4.19%,P,PPPPP,PPPPP,PPPPN,57
2,03-04-2009,842.50,4029.67,0.97%,-2.34%,N,PPPPN,PPPPN,PPPNP,63
3,06-04-2009,835.48,3993.54,-0.84%,-0.90%,P,PPPNP,PPPNP,PPNPP,59
4,07-04-2009,815.55,3930.52,-2.41%,-1.59%,P,PPNPP,PPNPP,PNPPN,26
...,...,...,...,...,...,...,...,...,...,...
1006,02-05-2013,1597.59,6460.71,0.94%,0.15%,P,PPNNP,PPNNP,PNNPP,18
1007,03-05-2013,1614.42,6521.46,1.05%,0.94%,P,PNNPP,PNNPP,NNPPP,19
1008,07-05-2013,1625.96,6557.30,0.71%,0.55%,P,NNPPP,NNPPP,NPPPP,12
1009,08-05-2013,1632.69,6583.48,0.41%,0.40%,P,NPPPP,NPPPP,PPPPN,21
1010,09-05-2013,1626.67,6592.74,-0.37%,0.14%,N,PPPPN,PPPPN,PPPNP,63

In [79]:
#Pulling out the source nodes, target nodes and weights from the post crisis dataframe

fcb_postdata2 = fcb_postdata.loc[:,["Source","Target","Weights"]]
fcb_postdata2

     Source Target  Weights
0     PPPPP  PPPPP      116
1     PPPPP  PPPPN       57
2     PPPPN  PPPNP       63
3     PPPNP  PPNPP       59
4     PPNPP  PNPPN       26
...     ...    ...      ...
1006  PPNNP  PNNPP       18
1007  PNNPP  NNPPP       19
1008  NNPPP  NPPPP       12
1009  NPPPP  PPPPN       21
1010  PPPPN  PPPNP       63

[1011 rows x 3 columns]

In [80]:
#Drawing out the network structure for post crisis dataframe

G_postdata = nx.from_pandas_edgelist(fcb_postdata2,source='Source',target='Target', edge_attr='Weights', create_using=nx.DiGraph())
print(G_postdata)

DiGraph with 31 nodes and 61 edges

## 5. Calculation of network measures for each of the four networks formed

### 5.1 'All Data' Dataset

In [81]:
#Calculating Outdegree of all data

outdegree1 = G_alldata.out_degree (weight = 'Weights')
G_alldata_od = pd.DataFrame.from_dict(outdegree1)
G_alldata_od.columns = ['Nodes', 'Degree']
G_alldata_od2 = G_alldata_od.sort_values('Degree', ascending = False, ignore_index = True)
G_alldata_od2

    Nodes  Degree
0   PPPPP     272
1   PPNPP     145
2   PNPPP     140
3   PPPNP     138
4   NPPPP     134
5   PPPPN     134
6   NPPNP      62
7   PNPNP      60
8   PNPPN      58
9   PNNPP      57
10  NPPPN      56
11  PPNPN      55
12  NPNPP      53
13  PPNNP      53
14  PPPNN      51
15  NNPPP      50
16  NPNPN      29
17  NNPPN      27
18  PNPNN      24
19  NPNNP      23
20  NPPNN      23
21  PNNNP      22
22  NNPNP      21
23  PPNNN      21
24  NNNPP      20
25  PNNPN      19
26  NNNPN      13
27  NPNNN      12
28  NNNNP      11
29  PNNNN      11
30  NNPNN      11
31  NNNNN       4

In [82]:
#Calculating degree distribution
dd1 = G_alldata_od2['Degree'].value_counts(normalize=True)
dd1_df1 = pd.DataFrame (dd1, columns = ['Degree'])
dd1_df2 = dd1_df1.reset_index(level=0)
dd1_df2.columns = ['Degree', 'Distribution of Degree']
dd1_df2

    Degree  Distribution of Degree
0       11                 0.09375
1      134                 0.06250
2       21                 0.06250
3       23                 0.06250
4       53                 0.06250
5      272                 0.03125
6       29                 0.03125
7       12                 0.03125
8       13                 0.03125
9       19                 0.03125
10      20                 0.03125
11      22                 0.03125
12      24                 0.03125
13      27                 0.03125
14      50                 0.03125
15     145                 0.03125
16      51                 0.03125
17      55                 0.03125
18      56                 0.03125
19      57                 0.03125
20      58                 0.03125
21      60                 0.03125
22      62                 0.03125
23     138                 0.03125
24     140                 0.03125
25       4                 0.03125

In [83]:
#Merging outdegree and distribution dataframes based of degree values

G_alldata_od3 = pd.merge(G_alldata_od2, dd1_df2, on="Degree")
G_alldata_od3

    Nodes  Degree  Distribution of Degree
0   PPPPP     272                 0.03125
1   PPNPP     145                 0.03125
2   PNPPP     140                 0.03125
3   PPPNP     138                 0.03125
4   NPPPP     134                 0.06250
5   PPPPN     134                 0.06250
6   NPPNP      62                 0.03125
7   PNPNP      60                 0.03125
8   PNPPN      58                 0.03125
9   PNNPP      57                 0.03125
10  NPPPN      56                 0.03125
11  PPNPN      55                 0.03125
12  NPNPP      53                 0.06250
13  PPNNP      53                 0.06250
14  PPPNN      51                 0.03125
15  NNPPP      50                 0.03125
16  NPNPN      29                 0.03125
17  NNPPN      27                 0.03125
18  PNPNN      24                 0.03125
19  NPNNP      23                 0.06250
20  NPPNN      23                 0.06250
21  PNNNP      22                 0.03125
22  NNPNP      21                 0.06250
23  PPNNN      21                 0.06250
24  NNNPP      20                 0.03125
25  PNNPN      19                 0.03125
26  NNNPN      13                 0.03125
27  NPNNN      12                 0.03125
28  NNNNP      11                 0.09375
29  PNNNN      11                 0.09375
30  NNPNN      11                 0.09375
31  NNNNN       4                 0.03125

In [84]:
#Calculating clustering coefficient, betweenness centrality and closeness centrality of all data

#Clustering Coefficient
cl1 = nx.clustering(G_alldata, weight='Weights')
cl1_df1 = pd.DataFrame(cl1.items(), columns=['Nodes', 'Clustering Coefficient'])

#Betweenness Centrality
bc1 = nx.betweenness_centrality(G_alldata, weight = 'Weights')
bc1_df1 = pd.DataFrame(bc1.items(), columns=['Nodes', 'Betweenness Centrality'])

#Closeness Centrality
cc1 = nx.closeness_centrality(G_alldata, distance = 'Weights')
cc1_df1 = pd.DataFrame(cc1.items(), columns=['Nodes', 'Closeness Centrality'])

In [85]:
#Merging clustering, betweenness and closeness with G_alldata_od3

G_alldata_od4 = pd.merge(G_alldata_od3, cl1_df1, on="Nodes")
G_alldata_od5 = pd.merge(G_alldata_od4, bc1_df1, on="Nodes")
G_alldata_od6 = pd.merge(G_alldata_od5, cc1_df1, on="Nodes")
G_alldata_od6

,Nodes,Degree,Distribution of Degree,Clustering Coefficient,Betweenness Centrality,Closeness Centrality
0,PPPPP,272,0.03125,0.201684,0.000000,0.005886
1,PPNPP,145,0.03125,0.020567,0.001075,0.009182
2,PNPPP,140,0.03125,0.000000,0.003226,0.010712
3,PPPNP,138,0.03125,0.000000,0.003226,0.010406
4,NPPPP,134,0.06250,0.033614,0.063441,0.012757
5,PPPPN,134,0.06250,0.033614,0.063441,0.009383
6,NPPNP,62,0.03125,0.020567,0.059140,0.014405
7,PNPNP,60,0.03125,0.000000,0.003226,0.013231
8,PNPPN,58,0.03125,0.020567,0.065591,0.014976
9,PNNPP,57,0.03125,0.000000,0.007527,0.015947
10,NPPPN,56,0.03125,0.000000,0.111828,0.015181
11,PPNPN,55,0.03125,0.000000,0.061290,0.012643
12,NPNPP,53,0.06250,0.000000,0.067742,0.017118
13,PPNNP,53,0.06250,0.000000,0.007527,0.016551
14,PPPNN,51,0.03125,0.000000,0.172043,0.013124
15,NNPPP,50,0.03125,0.000000,0.172043,0.019339
16,NPNPN,29,0.03125,0.000000,0.106452,0.017465
17,NNPPN,27,0.03125,0.000000,0.180645,0.018630
18,PNPNN,24,0.03125,0.000000,0.164516,0.017348
19,NPNNP,23,0.06250,0.003352,0.062366,0.020571
20,NPPNN,23,0.06250,0.000000,0.187097,0.018926
21,PNNNP,22,0.03125,0.000000,0.000000,0.023737
22,NNPNP,21,0.06250,0.000000,0.170968,0.019834
23,PPNNN,21,0.06250,0.000000,0.351613,0.020000
24,NNNPP,20,0.03125,0.000000,0.345161,0.021970
25,PNNPN,19,0.03125,0.003352,0.062366,0.019745
26,NNNPN,13,0.03125,0.000000,0.281720,0.022238
27,NPNNN,12,0.03125,0.000000,0.275269,0.022562
28,NNNNP,11,0.09375,0.001992,0.626882,0.024219
29,PNNNN,11,0.09375,0.001992,0.626882,0.027337
30,NNPNN,11,0.09375,0.003352,0.173118,0.021678
31,NNNNN,4,0.03125,0.011955,0.626882,0.025684

In [86]:
#Count number of nodes with '0' clustering coefficient

count1 = (G_alldata_od6['Clustering Coefficient'] == 0).sum()
count1

20

In [87]:
#Finding the node with the highest clustering coefficient

G_alldata_od6[G_alldata_od6['Clustering Coefficient']==G_alldata_od6['Clustering Coefficient'].max()]

,Nodes,Degree,Distribution of Degree,Clustering Coefficient,Betweenness Centrality,Closeness Centrality
0,PPPPP,272,0.03125,0.201684,0.0,0.005886

In [88]:
#Finding the node with the highest and least betweenness centrality

G_alldata_od6[G_alldata_od6['Betweenness Centrality']==G_alldata_od6['Betweenness Centrality'].max()]

,Nodes,Degree,Distribution of Degree,Clustering Coefficient,Betweenness Centrality,Closeness Centrality
28,NNNNP,11,0.09375,0.001992,0.626882,0.024219
29,PNNNN,11,0.09375,0.001992,0.626882,0.027337
31,NNNNN,4,0.03125,0.011955,0.626882,0.025684

In [89]:
G_alldata_od6[G_alldata_od6['Betweenness Centrality']==G_alldata_od6['Betweenness Centrality'].min()]

,Nodes,Degree,Distribution of Degree,Clustering Coefficient,Betweenness Centrality,Closeness Centrality
0,PPPPP,272,0.03125,0.201684,0.0,0.005886
21,PNNNP,22,0.03125,0.000000,0.0,0.023737

In [90]:
#Finding the node with the highest and least closeness centrality
G_alldata_od6[G_alldata_od6['Closeness Centrality']==G_alldata_od6['Closeness Centrality'].max()]

,Nodes,Degree,Distribution of Degree,Clustering Coefficient,Betweenness Centrality,Closeness Centrality
29,PNNNN,11,0.09375,0.001992,0.626882,0.027337

In [91]:
G_alldata_od6[G_alldata_od6['Closeness Centrality']==G_alldata_od6['Closeness Centrality'].min()]

,Nodes,Degree,Distribution of Degree,Clustering Coefficient,Betweenness Centrality,Closeness Centrality
0,PPPPP,272,0.03125,0.201684,0.0,0.005886

### 5.2 Pre-Crisis Dataset

In [92]:
#Calculating Outdegree of pre-crisis data

outdegree2 = G_predata.out_degree (weight = 'Weights')
G_predata_od = pd.DataFrame.from_dict(outdegree2)
G_predata_od.columns = ['Nodes', 'Degree']
G_predata_od2 = G_predata_od.sort_values('Degree', ascending = False, ignore_index = True)
G_predata_od2

    Nodes  Degree
0   PPPPP      34
1   PNPPP      19
2   PPPNP      18
3   NPPPP      17
4   PPPPN      17
5   PPNPP      17
6   PNNPP      14
7   PPNNP      13
8   PPNPN      13
9   NPPPN      12
10  NPPNP      12
11  PNPNP      12
12  NPNPP      11
13  PPPNN      11
14  NNPPP      10
15  NNPPN       9
16  PNPPN       9
17  PNNNP       6
18  NPPNN       6
19  NNNPP       6
20  NPNNP       4
21  NPNNN       4
22  PNPNN       4
23  NNPNN       4
24  PPNNN       4
25  PNNPN       3
26  NPNPN       3
27  NNNPN       2
28  NNNNP       2
29  NNNNN       2
30  PNNNN       2
31  NNPNP       1

In [93]:
#Calculating degree distribution
dd2 = G_predata_od2['Degree'].value_counts(normalize=True)
dd2_df1 = pd.DataFrame (dd2, columns = ['Degree'])
dd2_df2 = dd2_df1.reset_index(level=0)
dd2_df2.columns = ['Degree', 'Distribution of Degree']
dd2_df2

    Degree  Distribution of Degree
0        4                 0.15625
1        2                 0.12500
2       17                 0.09375
3       12                 0.09375
4        6                 0.09375
5       13                 0.06250
6       11                 0.06250
7        9                 0.06250
8        3                 0.06250
9       34                 0.03125
10      19                 0.03125
11      18                 0.03125
12      14                 0.03125
13      10                 0.03125
14       1                 0.03125

In [94]:
#Merging outdegree and distribution dataframes based of degree values

G_predata_od3 = pd.merge(G_predata_od2, dd2_df2, on="Degree")
G_predata_od3

    Nodes  Degree  Distribution of Degree
0   PPPPP      34                 0.03125
1   PNPPP      19                 0.03125
2   PPPNP      18                 0.03125
3   NPPPP      17                 0.09375
4   PPPPN      17                 0.09375
5   PPNPP      17                 0.09375
6   PNNPP      14                 0.03125
7   PPNNP      13                 0.06250
8   PPNPN      13                 0.06250
9   NPPPN      12                 0.09375
10  NPPNP      12                 0.09375
11  PNPNP      12                 0.09375
12  NPNPP      11                 0.06250
13  PPPNN      11                 0.06250
14  NNPPP      10                 0.03125
15  NNPPN       9                 0.06250
16  PNPPN       9                 0.06250
17  PNNNP       6                 0.09375
18  NPPNN       6                 0.09375
19  NNNPP       6                 0.09375
20  NPNNP       4                 0.15625
21  NPNNN       4                 0.15625
22  PNPNN       4                 0.15625
23  NNPNN       4                 0.15625
24  PPNNN       4                 0.15625
25  PNNPN       3                 0.06250
26  NPNPN       3                 0.06250
27  NNNPN       2                 0.12500
28  NNNNP       2                 0.12500
29  NNNNN       2                 0.12500
30  PNNNN       2                 0.12500
31  NNPNP       1                 0.03125

In [95]:
#Calculating clustering coefficient, betweenness centrality and closeness centrality of all data

#Clustering Coefficient
cl2 = nx.clustering(G_predata, weight='Weights')
cl2_df1 = pd.DataFrame(cl2.items(), columns=['Nodes', 'Clustering Coefficient'])

#Betweenness Centrality
bc2 = nx.betweenness_centrality(G_predata, weight = 'Weights')
bc2_df1 = pd.DataFrame(bc2.items(), columns=['Nodes', 'Betweenness Centrality'])

#Closeness Centrality
cc2 = nx.closeness_centrality(G_predata, distance = 'Weights')
cc2_df1 = pd.DataFrame(cc2.items(), columns=['Nodes', 'Closeness Centrality'])

In [96]:
#Merging clustering, betweenness and closeness with G_predata_od3

G_predata_od4 = pd.merge(G_predata_od3, cl2_df1, on="Nodes")
G_predata_od5 = pd.merge(G_predata_od4, bc2_df1, on="Nodes")
G_predata_od6 = pd.merge(G_predata_od5, cc2_df1, on="Nodes")
G_predata_od6

,Nodes,Degree,Distribution of Degree,Clustering Coefficient,Betweenness Centrality,Closeness Centrality
0,PPPPP,34,0.03125,0.209443,0.000000,0.032025
1,PNPPP,19,0.03125,0.000000,0.037097,0.037897
2,PPPNP,18,0.03125,0.000000,0.031183,0.045723
3,NPPPP,17,0.09375,0.034907,0.063441,0.054577
4,PPPPN,17,0.09375,0.034907,0.063441,0.050162
5,PPNPP,17,0.09375,0.023526,0.046774,0.046407
6,PNNPP,14,0.03125,0.000000,0.105376,0.064182
7,PPNNP,13,0.06250,0.000000,0.032258,0.062626
8,PPNPN,13,0.06250,0.000000,0.067204,0.049206
9,NPPPN,12,0.09375,0.000000,0.111828,0.061386
10,NPPNP,12,0.09375,0.023526,0.082796,0.054674
11,PNPNP,12,0.09375,0.000000,0.126882,0.075426
12,NPNPP,11,0.06250,0.000000,0.122581,0.044034
13,PPPNN,11,0.06250,0.000000,0.144086,0.054101
14,NNPPP,10,0.03125,0.000000,0.138172,0.074163
15,NNPPN,9,0.06250,0.000000,0.220430,0.064854
16,PNPPN,9,0.06250,0.023526,0.132258,0.045655
17,PNNNP,6,0.09375,0.000000,0.311290,0.087819
18,NPPNN,6,0.09375,0.000000,0.269892,0.069977
19,NNNPP,6,0.09375,0.000000,0.253226,0.076167
20,NPNNP,4,0.15625,0.000000,0.093548,0.082667
21,NPNNN,4,0.15625,0.000000,0.115591,0.080519
22,PNPNN,4,0.15625,0.000000,0.055376,0.042408
23,NNPNN,4,0.15625,0.000000,0.153763,0.085873
24,PPNNN,4,0.15625,0.000000,0.381720,0.076923
25,PNNPN,3,0.06250,0.000000,0.020430,0.054482
26,NPNPN,3,0.06250,0.000000,0.115054,0.092537
27,NNNPN,2,0.12500,0.000000,0.244086,0.087819
28,NNNNP,2,0.12500,0.004167,0.186022,0.067391
29,NNNNN,2,0.12500,0.025000,0.000000,0.065678
30,PNNNN,2,0.12500,0.008333,0.186022,0.068282
31,NNPNP,1,0.03125,0.000000,0.110753,0.086592

In [97]:
#Count number of nodes with '0' clustering coefficient

count2 = (G_predata_od6['Clustering Coefficient'] == 0).sum()
count2

23

In [98]:
#Finding the node with the highest clustering coefficient

G_predata_od6[G_predata_od6['Clustering Coefficient']==G_predata_od6['Clustering Coefficient'].max()]

,Nodes,Degree,Distribution of Degree,Clustering Coefficient,Betweenness Centrality,Closeness Centrality
0,PPPPP,34,0.03125,0.209443,0.0,0.032025

In [99]:
#Finding the node with the highest and least betweenness centrality

G_predata_od6[G_predata_od6['Betweenness Centrality']==G_predata_od6['Betweenness Centrality'].max()]

,Nodes,Degree,Distribution of Degree,Clustering Coefficient,Betweenness Centrality,Closeness Centrality
24,PPNNN,4,0.15625,0.0,0.38172,0.076923

In [100]:
G_predata_od6[G_predata_od6['Betweenness Centrality']==G_predata_od6['Betweenness Centrality'].min()]

,Nodes,Degree,Distribution of Degree,Clustering Coefficient,Betweenness Centrality,Closeness Centrality
0,PPPPP,34,0.03125,0.209443,0.0,0.032025
29,NNNNN,2,0.12500,0.025000,0.0,0.065678

In [101]:
#Finding the node with the highest and least closeness centrality

G_predata_od6[G_predata_od6['Closeness Centrality']==G_predata_od6['Closeness Centrality'].max()]

,Nodes,Degree,Distribution of Degree,Clustering Coefficient,Betweenness Centrality,Closeness Centrality
26,NPNPN,3,0.0625,0.0,0.115054,0.092537

In [102]:
G_predata_od6[G_predata_od6['Closeness Centrality']==G_predata_od6['Closeness Centrality'].min()]

,Nodes,Degree,Distribution of Degree,Clustering Coefficient,Betweenness Centrality,Closeness Centrality
0,PPPPP,34,0.03125,0.209443,0.0,0.032025

### 5.3 During-Crisis Dataset

In [103]:
#Calculating Outdegree of during-crisis data

outdegree3 = G_duringdata.out_degree (weight = 'Weights')
G_duringdata_od = pd.DataFrame.from_dict(outdegree3)
G_duringdata_od.columns = ['Nodes', 'Degree']
G_duringdata_od2 = G_duringdata_od.sort_values('Degree', ascending = False, ignore_index = True)
G_duringdata_od2

    Nodes  Degree
0   PPPPP      65
1   PPNPP      44
2   NPPPP      39
3   PPPPN      39
4   PPPNP      38
5   PNPPP      38
6   PNPPN      18
7   NPPNP      17
8   PNNPP      16
9   NNPPP      15
10  PPNNP      15
11  PPPNN      15
12  NPPPN      14
13  PNPNP      13
14  NPNPP      12
15  PPNPN      11
16  NPPNN       8
17  PPNNN       8
18  NPNPN       8
19  NNPPN       7
20  NNPNP       7
21  NNNNP       7
22  PNNNN       7
23  NNNPP       6
24  PNPNN       6
25  NNNPN       5
26  PNNNP       4
27  NPNNP       4
28  NPNNN       3
29  PNNPN       3
30  NNNNN       2
31  NNPNN       1

In [104]:
#Calculating degree distribution
dd3 = G_duringdata_od2['Degree'].value_counts(normalize=True)
dd3_df1 = pd.DataFrame (dd3, columns = ['Degree'])
dd3_df2 = dd3_df1.reset_index(level=0)
dd3_df2.columns = ['Degree', 'Distribution of Degree']
dd3_df2

    Degree  Distribution of Degree
0        7                 0.12500
1        8                 0.09375
2       15                 0.09375
3       39                 0.06250
4       38                 0.06250
5        3                 0.06250
6        4                 0.06250
7        6                 0.06250
8       65                 0.03125
9        2                 0.03125
10       5                 0.03125
11      12                 0.03125
12      11                 0.03125
13      44                 0.03125
14      13                 0.03125
15      14                 0.03125
16      16                 0.03125
17      17                 0.03125
18      18                 0.03125
19       1                 0.03125

In [105]:
#Merging outdegree and distribution dataframes based of degree values

G_duringdata_od3 = pd.merge(G_duringdata_od2, dd3_df2, on="Degree")
G_duringdata_od3

    Nodes  Degree  Distribution of Degree
0   PPPPP      65                 0.03125
1   PPNPP      44                 0.03125
2   NPPPP      39                 0.06250
3   PPPPN      39                 0.06250
4   PPPNP      38                 0.06250
5   PNPPP      38                 0.06250
6   PNPPN      18                 0.03125
7   NPPNP      17                 0.03125
8   PNNPP      16                 0.03125
9   NNPPP      15                 0.09375
10  PPNNP      15                 0.09375
11  PPPNN      15                 0.09375
12  NPPPN      14                 0.03125
13  PNPNP      13                 0.03125
14  NPNPP      12                 0.03125
15  PPNPN      11                 0.03125
16  NPPNN       8                 0.09375
17  PPNNN       8                 0.09375
18  NPNPN       8                 0.09375
19  NNPPN       7                 0.12500
20  NNPNP       7                 0.12500
21  NNNNP       7                 0.12500
22  PNNNN       7                 0.12500
23  NNNPP       6                 0.06250
24  PNPNN       6                 0.06250
25  NNNPN       5                 0.03125
26  PNNNP       4                 0.06250
27  NPNNP       4                 0.06250
28  NPNNN       3                 0.06250
29  PNNPN       3                 0.06250
30  NNNNN       2                 0.03125
31  NNPNN       1                 0.03125

In [106]:
#Calculating clustering coefficient, betweenness centrality and closeness centrality of all data

#Clustering Coefficient
cl3 = nx.clustering(G_duringdata, weight='Weights')
cl3_df1 = pd.DataFrame(cl3.items(), columns=['Nodes', 'Clustering Coefficient'])

#Betweenness Centrality
bc3 = nx.betweenness_centrality(G_duringdata, weight = 'Weights')
bc3_df1 = pd.DataFrame(bc3.items(), columns=['Nodes', 'Betweenness Centrality'])

#Closeness Centrality
cc3 = nx.closeness_centrality(G_duringdata, distance = 'Weights')
cc3_df1 = pd.DataFrame(cc3.items(), columns=['Nodes', 'Closeness Centrality'])

In [107]:
#Merging clustering, betweenness and closeness with G_duringdata_od3

G_duringdata_od4 = pd.merge(G_duringdata_od3, cl3_df1, on="Nodes")
G_duringdata_od5 = pd.merge(G_duringdata_od4, bc3_df1, on="Nodes")
G_duringdata_od6 = pd.merge(G_duringdata_od5, cc3_df1, on="Nodes")
G_duringdata_od6

,Nodes,Degree,Distribution of Degree,Clustering Coefficient,Betweenness Centrality,Closeness Centrality
0,PPPPP,65,0.03125,0.271117,0.000000,0.018289
1,PPNPP,44,0.03125,0.026965,0.000000,0.031282
2,NPPPP,39,0.06250,0.045186,0.063441,0.033769
3,PPPPN,39,0.06250,0.045186,0.063441,0.025578
4,PPPNP,38,0.06250,0.000000,0.012903,0.036993
5,PNPPP,38,0.06250,0.000000,0.017742,0.045190
6,PNPPN,18,0.03125,0.026965,0.070968,0.049759
7,NPPNP,17,0.03125,0.026965,0.076882,0.050000
8,PNNPP,16,0.03125,0.000000,0.117204,0.059730
9,NNPPP,15,0.09375,0.000000,0.157527,0.051926
10,PPNNP,15,0.09375,0.000000,0.046774,0.059615
11,PPPNN,15,0.09375,0.000000,0.162366,0.042234
12,NPPPN,14,0.03125,0.000000,0.111828,0.049521
13,PNPNP,13,0.03125,0.000000,0.003226,0.048137
14,NPNPP,12,0.03125,0.000000,0.088710,0.060904
15,PPNPN,11,0.03125,0.000000,0.089785,0.046757
16,NPPNN,8,0.09375,0.000000,0.199462,0.065539
17,PPNNN,8,0.09375,0.000000,0.315054,0.060429
18,NPNPN,8,0.09375,0.000000,0.126882,0.057621
19,NNPPN,7,0.12500,0.000000,0.205376,0.061144
20,NNPNP,7,0.12500,0.000000,0.212366,0.069820
21,NNNNP,7,0.12500,0.005953,0.173656,0.054577
22,PNNNN,7,0.12500,0.005953,0.173656,0.064315
23,NNNPP,6,0.06250,0.000000,0.245699,0.055957
24,PNPNN,6,0.06250,0.000000,0.213441,0.057514
25,NNNPN,5,0.03125,0.000000,0.184946,0.057944
26,PNNNP,4,0.06250,0.000000,0.256989,0.049521
27,NPNNP,4,0.06250,0.000000,0.170968,0.069042
28,NPNNN,3,0.06250,0.000000,0.115591,0.050736
29,PNNPN,3,0.06250,0.000000,0.100538,0.079487
30,NNNNN,2,0.03125,0.035716,0.173656,0.059048
31,NNPNN,1,0.03125,0.000000,0.073118,0.056777

In [108]:
#Count number of nodes with '0' clustering coefficient

count3 = (G_duringdata_od6['Clustering Coefficient'] == 0).sum()
count3

23

In [109]:
#Finding the node with the highest clustering coefficient

G_duringdata_od6[G_duringdata_od6['Clustering Coefficient']==G_duringdata_od6['Clustering Coefficient'].max()]

,Nodes,Degree,Distribution of Degree,Clustering Coefficient,Betweenness Centrality,Closeness Centrality
0,PPPPP,65,0.03125,0.271117,0.0,0.018289

In [110]:
#Finding the node with the highest and least betweenness centrality

G_duringdata_od6[G_duringdata_od6['Betweenness Centrality']==G_duringdata_od6['Betweenness Centrality'].max()]

,Nodes,Degree,Distribution of Degree,Clustering Coefficient,Betweenness Centrality,Closeness Centrality
17,PPNNN,8,0.09375,0.0,0.315054,0.060429

In [111]:
G_duringdata_od6[G_duringdata_od6['Betweenness Centrality']==G_duringdata_od6['Betweenness Centrality'].min()]

,Nodes,Degree,Distribution of Degree,Clustering Coefficient,Betweenness Centrality,Closeness Centrality
0,PPPPP,65,0.03125,0.271117,0.0,0.018289
1,PPNPP,44,0.03125,0.026965,0.0,0.031282

In [112]:
#Finding the node with the highest and least closeness centrality

G_duringdata_od6[G_duringdata_od6['Closeness Centrality']==G_duringdata_od6['Closeness Centrality'].max()]

,Nodes,Degree,Distribution of Degree,Clustering Coefficient,Betweenness Centrality,Closeness Centrality
29,PNNPN,3,0.0625,0.0,0.100538,0.079487

In [113]:
G_duringdata_od6[G_duringdata_od6['Closeness Centrality']==G_duringdata_od6['Closeness Centrality'].min()]

,Nodes,Degree,Distribution of Degree,Clustering Coefficient,Betweenness Centrality,Closeness Centrality
0,PPPPP,65,0.03125,0.271117,0.0,0.018289

### 5.4 Post-crisis dataset

In [114]:
#Calculating Outdegree of post-crisis data

outdegree4 = G_postdata.out_degree (weight = 'Weights')
G_postdata_od = pd.DataFrame.from_dict(outdegree4)
G_postdata_od.columns = ['Nodes', 'Degree']
G_postdata_od2 = G_postdata_od.sort_values('Degree', ascending = False, ignore_index = True)
G_postdata_od2

    Nodes  Degree
0   PPPPP     173
1   PPNPP      84
2   PNPPP      83
3   PPPNP      82
4   PPPPN      78
5   NPPPP      77
6   PNPNP      35
7   NPPNP      33
8   PPNPN      31
9   PNPPN      31
10  NPNPP      30
11  NPPPN      30
12  PNNPP      27
13  PPPNN      25
14  PPNNP      25
15  NNPPP      24
16  NPNPN      18
17  NPNNP      15
18  PNPNN      14
19  PNNPN      13
20  NNPNP      13
21  PNNNP      12
22  NNPPN      11
23  PPNNN       9
24  NPPNN       9
25  NNNPP       8
26  NNPNN       6
27  NNNPN       6
28  NPNNN       5
29  PNNNN       2
30  NNNNP       2

In [115]:
#Calculating degree distribution
dd4 = G_postdata_od2['Degree'].value_counts(normalize=True)
dd4_df1 = pd.DataFrame (dd4, columns = ['Degree'])
dd4_df2 = dd4_df1.reset_index(level=0)
dd4_df2.columns = ['Degree', 'Distribution of Degree']
dd4_df2

    Degree  Distribution of Degree
0        2                0.064516
1        6                0.064516
2        9                0.064516
3       31                0.064516
4       30                0.064516
5       13                0.064516
6       25                0.064516
7       15                0.032258
8        5                0.032258
9        8                0.032258
10      11                0.032258
11      12                0.032258
12      14                0.032258
13     173                0.032258
14      18                0.032258
15      84                0.032258
16      27                0.032258
17      33                0.032258
18      35                0.032258
19      77                0.032258
20      78                0.032258
21      82                0.032258
22      83                0.032258
23      24                0.032258

In [116]:
#Merging outdegree and distribution dataframes based of degree values

G_postdata_od3 = pd.merge(G_postdata_od2, dd4_df2, on="Degree")
G_postdata_od3

    Nodes  Degree  Distribution of Degree
0   PPPPP     173                0.032258
1   PPNPP      84                0.032258
2   PNPPP      83                0.032258
3   PPPNP      82                0.032258
4   PPPPN      78                0.032258
5   NPPPP      77                0.032258
6   PNPNP      35                0.032258
7   NPPNP      33                0.032258
8   PPNPN      31                0.064516
9   PNPPN      31                0.064516
10  NPNPP      30                0.064516
11  NPPPN      30                0.064516
12  PNNPP      27                0.032258
13  PPPNN      25                0.064516
14  PPNNP      25                0.064516
15  NNPPP      24                0.032258
16  NPNPN      18                0.032258
17  NPNNP      15                0.032258
18  PNPNN      14                0.032258
19  PNNPN      13                0.064516
20  NNPNP      13                0.064516
21  PNNNP      12                0.032258
22  NNPPN      11                0.032258
23  PPNNN       9                0.064516
24  NPPNN       9                0.064516
25  NNNPP       8                0.032258
26  NNPNN       6                0.064516
27  NNNPN       6                0.064516
28  NPNNN       5                0.032258
29  PNNNN       2                0.064516
30  NNNNP       2                0.064516

In [117]:
#Calculating clustering coefficient, betweenness centrality and closeness centrality of all data

#Clustering Coefficient
cl4 = nx.clustering(G_postdata, weight='Weights')
cl4_df1 = pd.DataFrame(cl4.items(), columns=['Nodes', 'Clustering Coefficient'])

#Betweenness Centrality
bc4 = nx.betweenness_centrality(G_postdata, weight = 'Weights')
bc4_df1 = pd.DataFrame(bc4.items(), columns=['Nodes', 'Betweenness Centrality'])

#Closeness Centrality
cc4 = nx.closeness_centrality(G_postdata, distance = 'Weights')
cc4_df1 = pd.DataFrame(cc4.items(), columns=['Nodes', 'Closeness Centrality'])

In [118]:
#Merging clustering, betweenness and closeness with G_duringdata_od3

G_postdata_od4 = pd.merge(G_postdata_od3, cl4_df1, on="Nodes")
G_postdata_od5 = pd.merge(G_postdata_od4, bc4_df1, on="Nodes")
G_postdata_od6 = pd.merge(G_postdata_od5, cc4_df1, on="Nodes")
G_postdata_od6

,Nodes,Degree,Distribution of Degree,Clustering Coefficient,Betweenness Centrality,Closeness Centrality
0,PPPPP,173,0.032258,0.175095,0.000000,0.011637
1,PPNPP,84,0.032258,0.017950,0.000000,0.019108
2,PNPPP,83,0.032258,0.000000,0.000000,0.019305
3,PPPNP,82,0.032258,0.000000,0.000000,0.019672
4,PPPPN,78,0.032258,0.029182,0.065517,0.019737
5,NPPPP,77,0.032258,0.029182,0.065517,0.030030
6,PNPNP,35,0.032258,0.000000,0.000000,0.025974
7,NPPNP,33,0.032258,0.017950,0.064368,0.033746
8,PPNPN,31,0.064516,0.000000,0.064368,0.028275
9,PNPPN,31,0.064516,0.017950,0.066092,0.030928
10,NPNPP,30,0.064516,0.000000,0.066092,0.034364
11,NPPPN,30,0.064516,0.000000,0.118391,0.030426
12,PNNPP,27,0.032258,0.000000,0.008046,0.031712
13,PPPNN,25,0.064516,0.000000,0.183908,0.026316
14,PPNNP,25,0.064516,0.000000,0.012069,0.036058
15,NNPPP,24,0.032258,0.000000,0.183908,0.043353
16,NPNPN,18,0.032258,0.000000,0.114368,0.038265
17,NPNNP,15,0.032258,0.003289,0.052299,0.042674
18,PNPNN,14,0.032258,0.000000,0.178736,0.037453
19,PNNPN,13,0.064516,0.003289,0.056322,0.035419
20,NNPNP,13,0.064516,0.000000,0.180460,0.044978
21,PNNNP,12,0.032258,0.000000,0.000000,0.045732
22,NNPPN,11,0.032258,0.000000,0.197126,0.046296
23,PPNNN,9,0.064516,0.000000,0.370690,0.048309
24,NPPNN,9,0.064516,0.000000,0.198851,0.044776
25,NNNPP,8,0.032258,0.000000,0.372989,0.051993
26,NNPNN,6,0.064516,0.003289,0.167241,0.049423
27,NNNPN,6,0.064516,0.000000,0.291379,0.051993
28,NPNNN,5,0.032258,0.000000,0.293678,0.049587
29,PNNNN,2,0.064516,0.000000,0.664368,0.059055
30,NNNNP,2,0.064516,0.000000,0.664368,0.053381

In [119]:
#Count number of nodes with '0' clustering coefficient

count4 = (G_postdata_od6['Clustering Coefficient'] == 0).sum()
count4

22

In [120]:
#Finding the node with the highest clustering coefficient

G_postdata_od6[G_postdata_od6['Clustering Coefficient']==G_postdata_od6['Clustering Coefficient'].max()]

,Nodes,Degree,Distribution of Degree,Clustering Coefficient,Betweenness Centrality,Closeness Centrality
0,PPPPP,173,0.032258,0.175095,0.0,0.011637

In [121]:
#Finding the node with the highest and least betweenness centrality

G_postdata_od6[G_postdata_od6['Betweenness Centrality']==G_postdata_od6['Betweenness Centrality'].max()]

,Nodes,Degree,Distribution of Degree,Clustering Coefficient,Betweenness Centrality,Closeness Centrality
29,PNNNN,2,0.064516,0.0,0.664368,0.059055
30,NNNNP,2,0.064516,0.0,0.664368,0.053381

In [122]:
G_postdata_od6[G_postdata_od6['Betweenness Centrality']==G_postdata_od6['Betweenness Centrality'].min()]

,Nodes,Degree,Distribution of Degree,Clustering Coefficient,Betweenness Centrality,Closeness Centrality
0,PPPPP,173,0.032258,0.175095,0.0,0.011637
1,PPNPP,84,0.032258,0.017950,0.0,0.019108
2,PNPPP,83,0.032258,0.000000,0.0,0.019305
3,PPPNP,82,0.032258,0.000000,0.0,0.019672
6,PNPNP,35,0.032258,0.000000,0.0,0.025974
21,PNNNP,12,0.032258,0.000000,0.0,0.045732

In [123]:
#Finding the node with the highest and least closeness centrality

G_postdata_od6[G_postdata_od6['Closeness Centrality']==G_postdata_od6['Closeness Centrality'].max()]

,Nodes,Degree,Distribution of Degree,Clustering Coefficient,Betweenness Centrality,Closeness Centrality
29,PNNNN,2,0.064516,0.0,0.664368,0.059055

In [124]:
G_postdata_od6[G_postdata_od6['Closeness Centrality']==G_postdata_od6['Closeness Centrality'].min()]

,Nodes,Degree,Distribution of Degree,Clustering Coefficient,Betweenness Centrality,Closeness Centrality
0,PPPPP,173,0.032258,0.175095,0.0,0.011637